# _config.yml
title: space
description: A personal site by Aryan Pandey from IIIT Jabalpur showcasing readings, projects, work experience, and travel notes.
url: "https://aryan1113.github.io"

theme: jekyll-theme-minimal

# Site settings
author: Aryan
email: aryanpandeywork@gmail.com
resume: https://t.co/ffNvoTIDow

# Social media links
twitter_url: "https://x.com/aisehiaryan"
github_url: "https://github.com/aryan1113"
hackmd_url: "http://hackmd.io/@aryan1113/"
medium_url: "http://medium.com/@aryan1113/"

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
permalink: /:title/

# Sections to display
sections:
  - about
  - interview-experiences
  - technical-notes
  - travel-ideas

plugins:
  - jekyll-sitemap

# For references to friends
friend:
  aryan_shrivastava:
    name: Aryan Shrivastava
    linkedin: https://www.linkedin.com/in/aryan-shrivastava23/
  armin_patel:
    name: Armin Patel
    linkedin: https://www.linkedin.com/in/arminpatel/
