name: Update Last Modified Dates

on:
  push:
    branches: ["*"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-dates:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # so we have full git history

      - name: Update last_modified front matter
        run: |
          # Loop over only the markdown files that were changed in the last commit
          for file in $(git diff --name-only --diff-filter=AM HEAD~1 HEAD -- '*.md' '*.markdown'); do
            # get last commit date for the file
            last_date=$(git log -1 --invert-grep --grep="chore(dates)" --format="%aI" -- "$file")


            # check if file has front matter
            if grep -q '^---' "$file"; then
              # if last_modified already exists, replace it
              if grep -q '^last_modified:' "$file"; then
                sed -i "s/^last_modified:.*/last_modified: $last_date/" "$file"
              else
                # insert last_modified after first --- line
                sed -i "/^---/a last_modified: $last_date" "$file"
              fi
            fi
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # Commit only if there are changes and add [skip ci] to the message
          if ! git diff --cached --quiet; then
            git commit -m "chore(dates): update last_modified dates [skip ci]"
            git push
          fi